extends Node

var languages = {
	"čeština":{
		"heavyattack":"Těžký útok",
		"breaks_shield":"Prolomí štít",
		"limited_by":"Omezeno ",
		"attack":"Útok",
		"interaction":"Interakce",
		"blocking":"Blokování",
		"aim":"Míření",
		"rake":"Hrabání",
		"left":"Vlevo",
		"right":"Vpravo",
		"jump":"Skok",
		"crouch":"Skrčení",
		"boss_warden_quote":"„Rozluč se svou rodinou spratku, vidíš je naposled“",
		"letter":"„Našli jste již ty hrábě, pro které jsem vás vyslal? Musíme je urychleně najít, za každou cenu. Potřebuji víc duší, pro můj magický experiment -  „metamorfózu“, přiveďte co nejvíce vesničanů, pokračujte v pátrání po mocné duši. Nadešel čas odvést Vladimírova otce. Dostavte se do mé pevnosti, ihned jakmile jej zadržíte. Podejte hlášení kapitánu _____.“",
		"start":"Začít hrát",
		"load":"Nahrát hru",
		"options":"Nastavení",
		"credits":"Autoři",
		"quit":"Ukončit hru",
		"bush_quest":"Ahoj, oni.... ukradli mi mé děti.... přineseš je zpátky, že mládenče?",
		"bush_thanks":"Oh děkuji mladíku",
		"continue":"Pokračovat",
		"new_game":"Nová hra",
		"save":"Uložit",
		"restart":"Restartovat u kontrolního bodu",
		"main_menu":"Hlavní menu",
		"audio":"Zvuk",
		"language":"Jazyk",
		"close":"Zavřít",
		"back":"Zpět",
		"master_volume":"Celková hlasitost ",
		"music_volume":"Hlasitost hudby ",
		"sfx_volume":"Efekty",
		"price":"Cena: ",
		"In the wood":"V lesích",
		"Dark forest":"Temný hvozd",
		"Cave entrance":"Vstup do jeskyně",
		"Mine shaft":"Důlní šachta",
		"Lil cave":"Jeskyňka",
		"Forest clearing":"Lesní mýtina",
		"Telpenor town":"Město Telpenor",
		"reset_keys":"Resetovat",
		"key_binding":"Ovládání",
		"health":"Životy",
		"damage:":"Poškození",
		"speed":"Rychlost Pohybu",
		"statiscitcs":"V předchozí úrovni jsi dosáhl: ",
		"time":"Čas: ",
		"date":"Datum: ",
		"overwrite":"přepsat",
		"quick_save":"F1, F2, F3 rychlé uložení",
		"loading":"N A Č Í T Á N Í",
		"f11":"Celá obrazovka",
		"r_btn":"Levé TLM",
		"l_btn":"Pravé TLM",
		"wrong_translation":"Pokud najdete špatný překlad, kontaktujte nás na emailu: ",
		"thanks":"Speciální poděkování:",
		"for_sound":"za poskytnutí zvukových efektů",
		"streamers":"Streamerům & YouTuberům za testování hry:",
		"boss1":"Dráb",
		"boss2":"vyvrhel Rudolf",
		"boss3":"hrabě Fridrich",
		"boss4":"Onihro",
		"mom":"To jsem ráda, že se ti nic nestalo. Vezmi si tohle, budeš to potřebovat",
	},
	"english":{
		"heavyattack":"Heavy Attack",
		"breaks_shield":"Breaks shield",
		"limited_by":"Limited by",
		"attack":"Attack",
		"interaction":"Interaction",
		"blocking":"Blocking",
		"aim":"Aiming",
		"rake":"Rake",
		"left":"Left",
		"right":"Right",
		"jump":"Jump",
		"crouch":"Crouch",
		"boss_warden_quote":"„Say goodbye to your family, brat. You see them for the last timenot“",
		"letter":"„Have you already found the rakes for which I sent you? We must find them quickly, at all costs. I need more souls, for my magical experiment - „metamorphosis“, bring as many villagers as possible, continue to search for a powerful soul. It's time to take Vladimir's father away. Come to my fortress as soon as you get him. Report to Captain _____.“",
		"start":"Start Game",
		"load":"Load Game",
		"options":"Settings",
		"credits":"Authors",
		"quit":"Quit",
		"bush_quest":"Hi, they .... stole my children .... will you bring them back, young man? ",
		"bush_thanks":"Oh thank you young man",
		"continue":"Continue",
		"new_game":"New Game",
		"save":"Save",
		"restart":"Restart at checkpoint",
		"main_menu":"Main menu",
		"audio":"Audio",
		"language":"Language",
		"close":"Close",
		"back":"Back",
		"master_volume":"Master volume ",
		"music_volume":"Music volume ",
		"sfx_volume":"Effects",
		"price":"Price: ",
		"In the wood":"In the wood",
		"Dark forest":"Dark forest",
		"Cave entrance":"Cave entrance",
		"Mine shaft":"Mine shaft",
		"Lil cave":"Lil cave",
		"Forest clearing":"Forest meadow",
		"Telpenor town":"Telpenor town",
		"reset_keys":"Reset keys",
		"key_binding":"Controls",
		"health":"Health",
		"damage:":"Damage",
		"speed":"Movement Speed",
		"statiscitcs":"In previous level you've accomplished:",
		"time":"Time: ",
		"date":"Date: ",
		"overwrite":"overwrite",
		"quick_save":"F1, F2, F3 to quick save",
		"loading":"L O A D I N G",
		"f11":"Fullscreen",
		"r_btn":"MB right",
		"l_btn":"MB left",
		"wrong_translation":"If you find wrong translation contact us on email: ",
		"thanks":"Special thanks to:",
		"for_sound":"for proving sound effects",
		"streamers":"Streamers & YouTubers for testing the game:",
		"boss1":"Supervisor",
		"boss2":"outcast Rudolph",
		"boss3":"count Friedrich",
		"boss4":"Onihro",
		"mom":"I'm glad that nothing happened to you. Take it, you will need it",
	},
	"polskie": {
		"heavyattack":"Ciężki atak",
		"breaks_shield":"Łamie tarczę",
		"limited_by":"Ograniczony przez",
		"attack":"Atak",
		"interaction":"Interakcja",
		"blocking":"Bloking",
		"aim":"Celować",
		"rake":"Amfiladowy",
		"left":"Lewo",
		"right":"Prawo",
		"jump":"Skok",
		"crouch":"Kucanie",
		"boss_warden_quote":"„Pożegnaj się z rodziną, bachor widzisz ich po raz ostatni“",
		"letter":"„Našli jste již ty hrábě, pro které jsem vás vyslal? Musíme je urychleně najít, za každou cenu. Potřebuji víc duší, pro můj magický experiment -  „metamorfózu“, přiveďte co nejvíce vesničanů, pokračujte v pátrání po mocné duši. Nadešel čas odvést Vladimírova otce. Dostavte se do mé pevnosti, ihned jakmile jej zadržíte. Podejte hlášení kapitánu _____.“",
		"start":"Zacząć grę",
		"load":"Wczytaj grę",
		"options":"Ustawienia",
		"credits":"Twórcy",
		"quit":"Zakończyć grę",
		"bush_quest":"Cześć, oni ... ukradli moje dzieci ... przyniesiesz je z powrotem, prawda, chłopcze?",
		"bush_thanks":"Och, dziękuję młody człowieku",
		"continue":"Kontyntynuj",
		"new_game":"Nowa gra",
		"save":"Zapisz grę",
		"restart":"Uruchom ponownie w punkcie kontrolnym",
		"main_menu":"Menu główne",
		"audio":"Dźwięk",
		"language":"Język",
		"close":"Zamknij",
		"back":"Powrót",
		"master_volume":"Głośność ",
		"music_volume":"Głośność muzyki ",
		"sfx_volume":"Efekty",
		"price":"Cena: ",
		"In the wood":"W lasach",
		"Dark forest":"Ciemny las",
		"Cave entrance":"Wejście do jaskini",
		"Mine shaft":"Szyb górniczy",
		"Lil cave":"Mała jaskinia",
		"Forest clearing":"Leśna łąka",
		"Telpenor town":"Miasto Telpenor",
		"reset_keys":"Zresetować",
		"key_binding":"Sterowanie",
		"health":"Życie",
		"damage:":"Obrażenia",
		"speed":"Prędkość ruchu",
		"statiscitcs":"Na poprzednim poziomie osiągnąłeś: ",
		"time":"Czas: ",
		"date":"Data: ",
		"overwrite":"nadpisz",
		"quick_save":"F1, F2, F3 szybki zapis",
		"loading":"W C Z Y T Y W A N I E",
		"f11":"Pełny ekran",
		"r_btn":"Lewy PM",
		"l_btn":"Prawy PM",
		"wrong_translation":"Jeśli znajdziesz błędne tłumaczenie, skontaktuj się z nami na email: ",
		"thanks":"Szczególne podziękowania:",
		"for_sound":"za zapewnienie SFX",
		"streamers":"Streamerzy & YouTuberzy do testowania gry:",
		"boss1":"Nadzorca",
		"boss2":"wyrzutek Rudolf",
		"boss3":"hrabia Friedrich",
		"boss4":"Onihro",
		"mom":"Cieszę się, że nic ci się nie stało. Weź to, będziesz tego potrzebować",
	},
	"deutsch":{
		"heavyattack":"Schwerer angriff",
		"breaks_shield":"Schildbrecher",
		"limited_by":"Begrenzt durch",
		"attack":"Attacke",
		"interaction":"Interaktion",
		"blocking":"Blockierung",
		"aim":"Zielen",
		"rake":"Rechen",
		"left":"Links",
		"right":"Rechts",
		"jump":"Springen",
		"crouch":"Kriechen",
		"boss_warden_quote":"„Verabschiede dich von deiner Familie, du siehst sie zum letzten Mal“",
		"letter":"„“",
		"start":"Spielen",
		"load":"Laden",
		"options":"Optionen",
		"credits":"Autoren",
		"quit":"Beenden",
		"bush_quest":"Hi, sie ... sie haben meine Kinder gestohlen ... du bringst sie zurück, nicht wahr, Junge?",
		"bush_thanks":"Oh danke junger Mann",
		"continue":"Fortsetzen",
		"new_game":"Neues Spiel",
		"save":"Spiel speichern",
		"restart":"Neustart am Checkpoint",
		"main_menu":"Hauptmenü",
		"audio":"Musik",
		"language":"Sprache",
		"close":"Schließen",
		"back":"Zurück",
		"master_volume":"Lautstärke",
		"music_volume":"Musiklautstärke",
		"sfx_volume":"Soundeffektlautstärke",
		"price":"Preis: ",
		"In the wood":"Im Wald",
		"Dark forest":"Dunkler Wald",
		"Cave entrance":"Höhleneingang",
		"Mine shaft":"Minenschacht",
		"Lil cave":"Kleine Höhle",
		"Forest clearing":"Waldlichtung",
		"Telpenor town":"Stadt Telpenor",
		"reset_keys":"Reset",
		"key_binding":"Tastenbelegung",
		"health":"Gesundheit",
		"damage:":"Schaden",
		"speed":"Bewegungsgeschwindigkeit",
		"statiscitcs":"Auf der vorherigen Stufe haben Sie erreicht:",
		"time":"Zeit: ",
		"date":"Datum: ",
		"overwrite":"überschreiben",
		"quick_save":"F1, F2, F3 schnellspeichern",
		"loading":"L Ä D T",
		"f11":"Vollbild",
		"r_btn":"Rechte MT",
		"l_btn":"Linke MT",
		"wrong_translation":"Wenn Sie eine falsche Übersetzung finden, kontaktieren Sie uns bitte per E-Mail: ",
		"thanks":"Besonderer Dank an:",
		"for_sound":"zur Bereitstellung von Soundeffekten",
		"streamers":"Streamer und YouTuber zum Testen des Spiels:",
		"boss1":"Aufseher",
		"boss2":"ausgestoßener Rudolph",
		"boss3":"graf Friedrich",
		"boss4":"Onihro",
		"mom":"Ich bin froh, dass dir nichts passiert ist. Nimm es, du wirst es brauchen",
	},
	"slovenčina":{
		"heavyattack":"Silný útok",
		"breaks_shield":"Rozbije štít",
		"limited_by":"Obmedzené ",
		"attack":"Útok",
		"interaction":"Interakcie",
		"blocking":"Blokovanie",
		"aim":"Mierenie",
		"rake":"Hrabanie",
		"left":"Vľavo",
		"right":"Vpravo",
		"jump":"Skok",
		"crouch":"Skrčenie",
		"boss_warden_quote":"„Rozluč se svou rodinou spratku, vidíš je naposled“",
		"letter":"„“",
		"start":"Začať hrať",
		"load":"Načítať hru",
		"options":"Nastavenia",
		"credits":"Autori",
		"quit":"Ukončiť hru",
		"bush_quest":"Ahoj, oni.... ukradli mi moje deti.... prinesieš ich späť, že mládenče?",
		"bush_thanks":"Oh ďakujem chalan",
		"continue":"Pokračovať",
		"new_game":"Nová hra",
		"save":"Uložiť hru",
		"restart":"Reštartovať pri kontrolnom bode",
		"main_menu":"Hlavné menu",
		"audio":"Zvuk",
		"language":"Jazyk",
		"close":"Zavrieť",
		"back":"Späť",
		"master_volume":"Celková hlasitosť",
		"music_volume":"Hlasitosť hudby",
		"sfx_volume":"Efekty",
		"price":"Cena: ",
		"In the wood":"V lesoch",
		"Dark forest":"Temný hvozd",
		"Cave entrance":"Vchod do jaskyne",
		"Mine shaft":"Banská šachta",
		"Lil cave":"Jaskynka",
		"Forest clearing":"Lesná lúka",
		"Telpenor town":"Mesto telpenor",
		"reset_keys":"Resetovať",
		"key_binding":"Ovládanie",
		"health":"Životy",
		"damage:":"Poškodenie",
		"speed":"Rýchlosť pohybu",
		"statiscitcs":"V predchádzajúcej úrovni si dosiahol: ",
		"time":"Čas: ",
		"date":"Dátum: ",
		"overwrite":"prepísať",
		"quick_save":"F1, F2, F3 rýchle uloženie",
		"loading":"N A Č Í T Á N I E",
		"f11":"Celá obrazovka",
		"r_btn":"Pravé TLM",
		"l_btn":"Ľavé TLM",
		"wrong_translation":"Pokud najdete špatný překlad, kontaktujte nás na emailu: ",
		"thanks":"Špeciálne poďakovanie:",
		"for_sound":"za poskytnutie zvukových efektov",
		"streamers":"Streamerom a YouTuberom za testovanie hry:",
		"boss1":"Dozorca",
		"boss2":"vyhnanec Rudolf",
		"boss3":"gróf Fridrich",
		"boss4":"Onihro",
		"mom":"Som ráda, že sa ti nič nestalo. Vezmi si to, budeš to potrebovať",
	},
	"français":{
		"heavyattack":"Attaque lourde",
		"breaks_shield":"Brise le bouclier",
		"limited_by":"Limité par",
		"attack":"Attaquer",
		"interaction":"Interaction",
		"blocking":"Blocage",
		"aim":"Viser",
		"rake":"Ratisser",
		"left":"À gauche",
		"right":"À droite",
		"jump":"Sauter",
		"crouch":"S'accroupir",
		"boss_warden_quote":"„Dis au revoir à ta famille, gamin, C'est la dernière fois que tu les vois“",
		"letter":"„“",
		"start":"Jouer",
		"load":"Charger",
		"options":"Options",
		"credits":"Auteurs",
		"quit":"Quitter",
		"bush_quest":"Salut, ils... ils ont volé mes enfants... tu les ramènes, n'est-ce pas, mon garçon?",
		"bush_thanks":"Oh merci jeune homme",
		"continue":"Continuer",
		"new_game":"Nouveau jeu",
		"save":"Sauvegarder jeu",
		"restart":"Redémarrer au point de contrôle",
		"main_menu":"Menu principal",
		"audio":"l'audio",
		"language":"Langue",
		"close":"Fermer",
		"back":"Retour",
		"master_volume":"Volume total",
		"music_volume":"Volume de la musique",
		"sfx_volume":"Volume des effets",
		"price":"Prix: ",
		"In the wood":"Dans le bois",
		"Dark forest":"Forêt Noire",
		"Cave entrance":"L'entrée de la grotte",
		"Mine shaft":"Puits de mine",
		"Lil cave":"Petite grotte",
		"Forest clearing":"Prairie forestière",
		"Telpenor town":"La ville de Telpenor",
		"reset_keys":"Reset",
		"key_binding":"Contrôles",
		"health":"Santé",
		"damage:":"Dégâts",
		"speed":"Vitesse de mouvement",
		"statiscitcs":"Au niveau précédent, vous avez accompli: ",
		"time":"Temps: ",
		"date":"Date: ",
		"overwrite":"écraser la sauvegarde",
		"quick_save":"F1, F2, F3 sauvegarde rapide",
		"loading":"Ch a r g e m e n t",
		"f11":"Plein écran",
		"r_btn":"clic droit",
		"l_btn":"clic gauche",
		"wrong_translation":"Si vous trouvez une mauvaise traduction, contactez-nous par email: ",
		"thanks":"Remerciements spéciaux:",
		"for_sound":"pour fournir des effets sonores",
		"streamers":"Streamers & YouTubers pour tester le jeu:",
		"boss1":"Superviseur",
		"boss2":"paria Rodolphe",
		"boss3":"le comte Frédéric",
		"boss4":"Onihro",
		"mom":"Je suis content qu'il ne t'arrive rien. Prends-le, tu en auras besoin",
	},
	"italiano":{
		"heavyattack":"Attacco pesante",
		"breaks_shield":"Rompe lo scudo",
		"limited_by":"Limitato da",
		"attack":"Attacco",
		"interaction":"Interazione",
		"blocking":"Blocco",
		"aim":"Mirare",
		"rake":"Rastrello",
		"left":"Sinistra",
		"right":"Destra",
		"jump":"Saltare",
		"crouch":"Accovacciarsi",
		"boss_warden_quote":"„Dì addio alla tua famiglia, moccioso, guardali per l'ultima volta“",
		"letter":"„“",
		"start":"Gioca",
		"load":"Caricare",
		"options":"Opzioni",
		"credits":"Autori",
		"quit":"Esci",
		"bush_quest":"Ciao, loro... hanno rubato i miei bambini... li riporti indietro, vero, ragazzo?",
		"bush_thanks":"Oh grazie giovanotto",
		"continue":"Continua",
		"new_game":"Nuovo gioco",
		"save":"Salva",
		"restart":"Riavvia al checkpoint",
		"main_menu":"Menu principale",
		"audio":"Audio",
		"language":"Lingua",
		"close":"Chiudere",
		"back":"Indietro",
		"master_volume":"Volume totale",
		"music_volume":"Volume della musica",
		"sfx_volume":"Volume degli effetti sonori",
		"price":"Prezzo: ",
		"In the wood":"Nei boschi",
		"Dark forest":"Foresta oscura",
		"Cave entrance":"Ingresso alla grotta",
		"Mine shaft":"Pozzo minerario",
		"Lil cave":"Piccola grotta",
		"Forest clearing":"Prato della foresta",
		"Telpenor town":"La città di Telpenor",
		"reset_keys":"Ripristina",
		"key_binding":"Controllo",
		"health":"Salute",
		"damage:":"Danno",
		"speed":"Velocità di movimento",
		"statiscitcs":"Nel livello precedente hai raggiunto: ",
		"time":"Tempo: ",
		"date":"Data: ",
		"overwrite":"sovrascrivere",
		"quick_save":"F1, F2, F3 salvataggio veloce",
		"loading":"C A R I C A M E N T O",
		"f11":"Schermo intero",
		"r_btn":"Tasto des",
		"l_btn":"Tasto sin",
		"wrong_translation":"Se trovi una traduzione errata, contattaci via e-mail: ",
		"thanks":"Ringraziamenti speciali:",
		"for_sound":"per fornire effetti sonori",
		"streamers":"Streamer & YouTuber per testare il gioco:",
		"boss1":"Supervisore",
		"boss2":"emarginato Rudolph",
		"boss3":"conte Federico",
		"boss4":"Onihro",
		"mom":"Sono contento che non ti sia successo niente. Prendi questo, ne avrai bisogno",
	},
	"español":{
		"heavyattack":"Ataque pesado",
		"breaks_shield":"Rompe el escudo",
		"limited_by":"Limitado por",
		"attack":"Ataque",
		"interaction":"Interacción",
		"blocking":"Bloqueo",
		"aim":"Apuntar",
		"rake":"Rastrillar",
		"left":"Izquierda",
		"right":"Derecha",
		"jump":"Saltar",
		"crouch":"Agacharse",
		"boss_warden_quote":"„Dile adiós a tu familia, mocoso, porque sera la ultima vez que los veas“",
		"letter":"„“",
		"start":"Jugar",
		"load":"Cargar",
		"options":"Opciones",
		"credits":"Autores",
		"quit":"Cerrar",
		"bush_quest":"Hola, ellos ... me robaron a mis hijos ... tú los traerás de vuelta, muchacho?",
		"bush_thanks":"Oh, gracias muchacho",
		"continue":"Continuar",
		"new_game":"Juego nuevo",
		"save":"Guardar",
		"restart":"Reiniciar punto de control",
		"main_menu":"Menú principal",
		"audio":"Audio",
		"language":"Idioma",
		"close":"Cerrar",
		"back":"Volver",
		"master_volume":"Volumen total",
		"music_volume":"Volumen de la música",
		"sfx_volume":"Volumen de los efectos",
		"price":"Precio: ",
		"In the wood":"En el bosque",
		"Dark forest":"Bosque oscuro",
		"Cave entrance":"Entrada a la cueva",
		"Mine shaft":"Dentro de la Mina",
		"Lil cave":"Pequeña cueva",
		"Forest clearing":"Prado del bosque",
		"Telpenor town":"La ciudad de Telpenor",
		"reset_keys":"Restablecer",
		"key_binding":"Controles",
		"health":"Salud",
		"damage:":"Daño",
		"speed":"Velocidad de movimiento",
		"statiscitcs":"En el nivel anterior lograste: ",
		"time":"Tiempo: ",
		"date":"Fecha: ",
		"overwrite":"Sobrescribir",
		"quick_save":"F1, F2, F3 guardar rápido",
		"loading":"C A R G A N D O",
		"f11":"Pantalla completa",
		"r_btn":"Der raton",
		"l_btn":"Izq raton",
		"wrong_translation":"Si encuentra una traducción incorrecta, contáctenos por correo electrónico: ",
		"thanks":"Agradecimiento especiales a:",
		"for_sound":"para proporcionar efectos de sonido",
		"streamers":"Streamers & YouTubers que probaron el juego:",
		"boss1":"Supervisor",
		"boss2":"Rudolph marginado",
		"boss3":"conde Federico",
		"boss4":"Onihro",
		"mom":"Me alegro de que no te haya pasado nada. Tómalo, lo necesitarás",
	},
	"português":{
		"heavyattack":"Ataque pesado",
		"breaks_shield":"Quebra o escudo",
		"limited_by":"Limitado por ",
		"attack":"Ataque",
		"interaction":"Interação",
		"blocking":"Bloqueando",
		"aim":"Mirar",
		"rake":"Ancinho",
		"left":"Esquerda",
		"right":"Direita",
		"jump":"Saltar",
		"crouch":"Agachar",
		"boss_warden_quote":"„Diga adeus à sua família, pirralho, veja-os pela última vez“",
		"letter":"„“",
		"start":"Jogar",
		"load":"Carregar",
		"options":"Opções",
		"credits":"Autores",
		"quit":"Sair",
		"bush_quest":"Oi, eles ... eles roubaram meus filhos ... traga-os de volta, não é, rapaz?",
		"bush_thanks":"Oh obrigado jovem",
		"continue":"Continuar",
		"new_game":"Novo Jogo",
		"save":"Guardar",
		"restart":"Reinicie ponto de verificação",
		"main_menu":"Menu Principal",
		"audio":"Áudio",
		"language":"Linguagem",
		"close":"Fechar",
		"back":"Costas",
		"master_volume":"Volume total",
		"music_volume":"Volume da música",
		"sfx_volume":"Volume de efeitos",
		"price":"Preço",
		"In the wood":"Na floresta",
		"Dark forest":"Floresta Negra",
		"Cave entrance":"Entrada para caverna",
		"Mine shaft":"Eixo de mineração",
		"Lil cave":"Pequena caverna",
		"Forest clearing":"Prado florestal",
		"Telpenor town":"A cidade de telpenor",
		"reset_keys":"Redefinir",
		"key_binding":"Controlos",
		"health":"Vida",
		"damage:":"Dano",
		"speed":"Velocidade de movimento",
		"statiscitcs":"No nível anterior, você alcançou: ",
		"overwrite":"Sobrescrever",
		"time":"Tempo: ",
		"date":"Data: ",
		"quick_save":"F1, F2, F3 salvamento rápido",
		"loading":"A C A R R E G A R",
		"f11":"ela cheia",
		"r_btn":"Dto mouse",
		"l_btn":"Esqu mouse",
		"wrong_translation":"Se você encontrar uma tradução errada, entre em contato conosco por e-mail: ",
		"thanks":"Agradecimentos especiais:",
		"for_sound":"para fornecer efeitos sonoros",
		"streamers":"Streamers & YouTubers para testar o jogo:",
		"boss1":"Supervisor",
		"boss2":"pária Rudolph",
		"boss3":"conde Frederico",
		"boss4":"Onihro",
		"mom":"Estou feliz que nada aconteceu com você. Pegue, você vai precisar",
	},
	"norsk":{
		"heavyattack":"Tungt angrep",
		"breaks_shield":"Bryter skjoldet",
		"limited_by":"Begrenset av ",
		"attack":"Angrep",
		"interaction":"Interaksjon",
		"blocking":"Blokkering",
		"aim":"Sikte",
		"rake":"Å rake",
		"left":"Venstre",
		"right":"Høyre",
		"jump":"Hopp",
		"crouch":"Krøke",
		"boss_warden_quote":"„Si farvel til familien din, gutt, du ser dem for siste gang“",
		"letter":"„“",
		"start":"Spille",
		"load":"Laste Opp",
		"options":"Innstillinger",
		"credits":"Forfattere",
		"quit":"Slutt",
		"bush_quest":"Hei, de ... de stjal barna mine ... du bringer dem tilbake, vil du ikke, gutt?",
		"bush_thanks":"Å takk unge mann",
		"continue":"Fortsette",
		"new_game":"Nytt Spill",
		"save":"Lagre",
		"restart":"Start på nytt ved sjekkpunkt",
		"main_menu":"Hovedmeny",
		"audio":"Lyd",
		"language":"Språk",
		"close":"Steng",
		"back":"Tilbake",
		"master_volume":"Totalt volum",
		"music_volume":"Musikk Volum",
		"sfx_volume":"Effekt volum",
		"price":"Pris: ",
		"In the wood":"I skogen",
		"Dark forest":"Mørk skog",
		"Cave entrance":"Inngang til hulen",
		"Mine shaft":"Gruvesjakt",
		"Lil cave":"Liten hule",
		"Forest clearing":"Skogen eng",
		"Telpenor town":"Byen Telpenor",
		"reset_keys":"Nullstille",
		"key_binding":"Styre",
		"health":"Liv",
		"damage:":"Skade",
		"speed":"Bevegelsesfart",
		"statiscitcs":"På forrige nivå oppnådde du: ",
		"time":"Tid: ",
		"date":"Dato: ",
		"overwrite":"Overskriv",
		"quick_save":"F1, F2, F3 hurtiglagring",
		"loading":"L A S T E R",
		"f11":"Full skjerm",
		"r_btn":"Høyre mus",
		"l_btn":"Venstre mus",
		"wrong_translation":"Hvis du finner en feil oversettelse, kontakt oss på e-post:",
		"thanks":"Spesiell takk:",
		"for_sound":"for å gi lydeffekter",
		"streamers":"Streamere & YouTubere for å teste spillet:",
		"boss1":"Veileder",
		"boss2":"utvist Rudolf",
		"boss3":"grev Frederick",
		"boss4":"Onihro",
		"mom":"Jeg er glad det ikke skjedde med deg. Ta dette, du trenger det",
	},
	"svenska":{
		"heavyattack":"Stark attack",
		"breaks_shield":"Bryter skölden",
		"limited_by":"Begränsas av",
		"attack":"Attackera",
		"interaction":"Samspel",
		"blocking":"Blockering",
		"aim":"Att sikta",
		"rake":"Att kratta",
		"left":"Vänster",
		"right":"Höger",
		"jump":"Hoppa",
		"crouch":"Huka",
		"boss_warden_quote":"„Säg adjö till din familj, brat, se dem för sista gången“",
		"letter":"„“",
		"start":"Starta",
		"load":"Ladda",
		"options":"Inställningar",
		"credits":"Författare",
		"quit":"Avsluta",
		"bush_quest":"Hej, de ... de stal mina barn ... kommer du ta tillbaka dem, unge man?",
		"bush_thanks":"Åh tack unge man",
		"continue":"Fortsätt",
		"new_game":"Nytt spel",
		"save":"Spara spel",
		"restart":"Starta om vid kontrollpunkten",
		"main_menu":"Huvudmeny",
		"audio":"Musik",
		"language":"Språk",
		"close":"Stänga",
		"back":"Tillbaka",
		"master_volume":"Volym total",
		"music_volume":"Volym musik",
		"sfx_volume":"Volym ljudeffekter",
		"price":"Pris: ",
		"In the wood":"I skogen",
		"Dark forest":"Mörk skog",
		"Cave entrance":"Ingång till grottan",
		"Mine shaft":"Gruvschakt",
		"Lil cave":"Liten grotta",
		"Forest clearing":"Skogsäng",
		"Telpenor town":"Telpenor stad",
		"reset_keys":"Återställa",
		"key_binding":"Kontroller",
		"health":"Hälsa",
		"damage:":"Skada",
		"speed":"Rörelsehastighet",
		"statiscitcs":"På tidigare nivå har du uppnått:",
		"time":"Tid: ",
		"date":"Datum: ",
		"overwrite":"Skriva över",
		"quick_save":"F1, F2, F3 snabbspara",
		"loading":"L A D D A R",
		"f11":"Fullskärm",
		"r_btn":"Höger musk",
		"l_btn":"Vänster mus",
		"wrong_translation":"Om du hittar en felaktig översättning, kontakta oss via email: ",
		"thanks":"Speciellt tack till:",
		"for_sound":"för att ge ljudeffekter",
		"streamers":"Streamers & YouTubers för att testa spelet:",
		"boss1":"Handledare",
		"boss2":"utstötte Rudolph",
		"boss3":"greve Fredrik",
		"boss4":"Onihro",
		"mom":"Jag är glad att ingenting hände dig. Ta det här, du kommer att behöva det",
	},
	"dansk":{
		"heavyattack":"Kraftig angreb",
		"breaks_shield":"Bryder skjoldet",
		"limited_by":"Begrænset af",
		"attack":"Angreb",
		"interaction":"Interaktion",
		"blocking":"Blokering",
		"aim":"At sigte",
		"rake":"Rive",
		"left":"Venstre",
		"right":"Højre",
		"jump":"Hoppe",
		"crouch":"Krybe sammen",
		"boss_warden_quote":"„Sig farvel til din familie, møgunge, se dem for sidste gang“",
		"letter":"„“",
		"start":"Spil",
		"load":"Indlæs",
		"options":"Indstillinger",
		"credits":"Forfattere",
		"quit":"Afslut",
		"bush_quest":"Hej, de ... de stjal mine børn ... du bringer dem tilbage, gør du ikke, dreng?",
		"bush_thanks":"Åh tak unge mand",
		"continue":"Fortsæt",
		"new_game":"Nyt Spil",
		"save":"Gem Spil",
		"restart":"Genstart ved checkpoint",
		"main_menu":"Hovedmenu",
		"audio":"Lyd",
		"language":"Sprog",
		"close":"Luk",
		"back":"Tilbage",
		"master_volume":"Samlet volumen",
		"music_volume":"Musik volumen",
		"sfx_volume":"Lydeffekt volumen",
		"price":"Pris: ",
		"In the wood":"I skoven",
		"Dark forest":"Mørk skov",
		"Cave entrance":"Indgang til hulen",
		"Mine shaft":"Mineskakt",
		"Lil cave":"En lille hule",
		"Forest clearing":"Skoveng",
		"Telpenor town":"Byen Telpenor",
		"reset_keys":"Nulstil",
		"key_binding":"Tastindstillinger",
		"health":"Liv",
		"damage:":"Skade",
		"speed":"Bevægelseshastighed",
		"statiscitcs":"På det forrige niveau opnåede du: ",
		"time":"Tid: ",
		"date":"Dato: ",
		"overwrite":"Omskriv",
		"quick_save":"F1, F2, F3 hurtig lagring",
		"loading":"I N D L Æ S E R",
		"f11":"Fuld skærm",
		"r_btn":"Højre mus",
		"l_btn":"Venstre mus",
		"wrong_translation":"Hvis du finder en forkert oversættelse, kontakt os via e-mail: ",
		"thanks":"Specielt tak:",
		"for_sound":"for at give lydeffekter",
		"streamers":"Streamere & YouTubere til at teste spillet:",
		"boss1":"Tilsynsførende",
		"boss2":"udstødte Rudolph",
		"boss3":"grev Frederik",
		"boss4":"Onihro",
		"mom":"Jeg er glad for, at der ikke skete dig noget. Tag dette, du får brug for det",
	},
	"suomi":{
		"heavyattack":"Raskas hyökkäys",
		"breaks_shield":"Rikkoo suojan",
		"limited_by":"Rajoitettu",
		"attack":"Hyökkäys",
		"interaction":"Vuorovaikutus",
		"blocking":"Estäminen",
		"aim":"Tavoite",
		"rake":"Haravoida",
		"left":"Vasen",
		"right":"Oikea",
		"jump":"Hyppää",
		"crouch":"Kyyristy",
		"boss_warden_quote":"„Sano hyvästit perheellesi, kakara, näe heidät viimeisen kerran“",
		"letter":"„“",
		"start":"Pelaa",
		"load":"Lataa",
		"options":"Asetukset",
		"credits":"Tekijät",
		"quit":"Loppu",
		"bush_quest":"Hei, he... he varastivat lapseni... sinä tuot heidät takaisin, eikö niin, poika?",
		"bush_thanks":"Voi kiitos nuori mies",
		"continue":"Jatkaa",
		"new_game":"Uusi peli",
		"save":"Tallenna",
		"restart":"Käynnistä uudelleen tarkistus pisteestä",
		"main_menu":"Päävalikko",
		"audio":"Ääni",
		"language":"Kieli",
		"close":"Kiinni",
		"back":"Takaisin",
		"master_volume":"Kokonaisvoimakkuus",
		"music_volume":"Musiikin voimakkuus",
		"sfx_volume":"Ääniefektien voimakkuus",
		"price":"Hinta: ",
		"In the wood":"Metsässä",
		"Dark forest":"Tumma metsä",
		"Cave entrance":"Sisäänkäynti luolaan",
		"Mine shaft":"Kaivos Akseli",
		"Lil cave":"Pieni luola",
		"Forest clearing":"Metsän niitty",
		"Telpenor town":"Telpenor kaupunki",
		"reset_keys":"Nollaa",
		"key_binding":"Ohjausasetukset",
		"health":"Terveys",
		"damage:":"Vaurio",
		"speed":"Liikenopeus",
		"statiscitcs":"Edellisellä tasolla saavutit: ",
		"time":"Aika: ",
		"date":"Päiväys: ",
		"overwrite":"korvaa",
		"quick_save":"F1, F2, F3 nopea tallennus",
		"loading":"L A D A T A A N",
		"f11":"Koko näyttö",
		"r_btn":"Oikea hiiri",
		"l_btn":"Vasen hiiri",
		"wrong_translation":"Jos löydät väärän käännöksen, ota meihin yhteyttä sähköpostitse:",
		"thanks":"Erityiskiitokset:",
		"for_sound":"äänitehosteiden tuottamiseen",
		"streamers":"Streamerit & YouTuberit pelin testaamiseen:",
		"boss1":"Valvoja",
		"boss2":"hylätty Rudolph",
		"boss3":"kreivi Frederick",
		"boss4":"Onihro",
		"mom":"Olen iloinen, ettei sinulle tapahtunut mitään. Ota tämä, tarvitset sitä",
	},
}

func translate(texts, other_language):
	for key in texts.keys():
		texts[key].text = languages[other_language][key]
		
		if "bbcode_text" in texts[key]:
			texts[key].bbcode_text = "[center]"+languages[other_language][key]
