extends Node

var languages = {
	"čeština":{
		"heavyattack":"Těžký útok",
		"breaks_shield":"Prolomí štít",
		"limited_by":"Omezeno: ",
		"attack":"Útok",
		"interaction":"Interakce",
		"movement":"Pro pohyb použij [color=#004a23]tlačítka 'A' / 'D'[/color]",
		"blocking":"Blokování",
		"aim":"Míření",
		"rake":"Hrabání",
		"left":"Vlevo",
		"right":"Vpravo",
		"jump":"Skok",
		"crouch":"Skrčení",
		"boss_warden_quote":"„Rozluč se svou rodinou spratku, vidíš je naposlednot“",
		"letter":"„Našli jste již ty hrábě, pro které jsem vás vyslal? Musíme je urychleně najít, za každou cenu. Potřebuji víc duší, pro můj magický experiment -  „metamorfózu“, přiveďte co nejvíce vesničanů, pokračujte v pátrání po mocné duši. Nadešel čas odvést Vladimírova otce. Dostavte se do mé pevnosti, ihned jakmile jej zadržíte. Podejte hlášení kapitánu _____.“",
		"start":"Začít hrát",
		"load":"Nahrát hru",
		"options":"Nastavení",
		"achievements":"Úspěchy",
		"credits":"Autoři",
		"quit":"Ukončit hru",
		"bush_quest":"Ahoj, oni.... ukradli mi mé děti.... přineseš je zpátky, že mládenče?",
		"bush_thanks":"Oh děkuji mladíku",
		"pause":"Menu",
		"continue":"Pokračovat",
		"new_game":"Nová hra",
		"save":"Uložit",
		"restart":"Restartovat u kontrolního bodu",
		"main_menu":"Hlavní menu",
		"audio":"Zvuk",
		"language":"Jazyk",
		"close":"Zavřít",
		"back":"Zpět",
		"master_volume":"Celková hlasitost ",
		"music_volume":"Hlasitost hudby ",
		"sfx_volume":"Effekty",
		"price":"Cena: ",
		"In the wood":"V lesích",
		"Dark forest":"Temný hvozd",
		"Cave entrance":"Vstup do jeskyně",
		"Mine shaft":"Důlní šachta",
		"Lil cave":"Jeskyňka",
		"Forest clearing":"Lesní mýtina",
		"Telpenor town":"Město Telpenor",
		"reset_keys":"Resetovat",
		"key_binding":"Ovládání",
		"health":"Životy",
		"damage:":"Poškození",
		"speed":"Rychlost Pohybu",
		"statiscitcs":"V předchozím levelu jsi dosáhl: ",
		"timer":"V čase: ",
		"quick_save":"F1, F2, F3 rychlé uložení",
		"loading":"N A Č Í T Á N Í",
		"f11":"Režim okna",
		"r_btn":"Levé TLM",
		"l_btn":"Pravé TLM"
	},
	"english":{
		"heavyattack":"Heavy Attack",
		"breaks_shield":"Breaks shield",
		"limited_by":"Limited by",
		"attack":"Attack",
		"interaction":"Interaction",
		"movement":"[color=#004a23]Use 'A' / 'D' buttons[/color] to move",
		"blocking":"Blocking",
		"aim":"Aiming",
		"rake":"Rake",
		"left":"Left",
		"right":"Right",
		"jump":"Jump",
		"crouch":"Crouch",
		"boss_warden_quote":"„Say goodbye to your family, brat. You see them for the last timenot“",
		"letter":"„Have you already found the rakes for which I sent you? We must find them quickly, at all costs. I need more souls, for my magical experiment - „metamorphosis“, bring as many villagers as possible, continue to search for a powerful soul. It's time to take Vladimir's father away. Come to my fortress as soon as you get him. Report to Captain _____.“",
		"start":"Start Game",
		"load":"Load Game",
		"options":"Settings",
		"achievements":"Achievements",
		"credits":"Authors",
		"quit":"Quit",
		"bush_quest":"Hi, they .... stole my children .... will you bring them back, young man? ",
		"bush_thanks":"Oh thank you young man",
		"pause":"Menu",
		"continue":"Continue",
		"new_game":"New Game",
		"save":"Save",
		"restart":"Restart at checkpoint",
		"main_menu":"Main menu",
		"audio":"Audio",
		"language":"Language",
		"close":"Close",
		"back":"Back",
		"master_volume":"Master volume ",
		"music_volume":"Music volume ",
		"sfx_volume":"Effects",
		"price":"Price: ",
		"In the wood":"In the wood",
		"Dark forest":"Dark forest",
		"Cave entrance":"Cave entrance",
		"Mine shaft":"Mine shaft",
		"Lil cave":"Lil cave",
		"Forest clearing":"Forest clearing",
		"Telpenor town":"Telpenor town",
		"reset_keys":"Reset keys",
		"key_binding":"Controls",
		"health":"Health",
		"damage:":"Damage",
		"speed":"Movement Speed",
		"statiscitcs":"In previous level you've accomplished:",
		"timer":"In time: ",
		"quick_save":"F1, F2, F3 to quick save",
		"loading":"L O A D I N G",
		"f11":"Windowed mode",
		"r_btn":"MB right",
		"l_btn":"MB left"
	},
	"polskie": {
		"start":"Zacząć gre",
		"load":"Wczytaj grę",
		"options":"Ustawienia",
		"achievements":"Osiągnięcia",
		"credits":"Autorski",
		"quit":"Zakończyć grę",
	},
	"deutsche":{
		"start":"Spiel beginnen",
		"load":"Spiel laden",
		"options":"Einstellungen",
		"achievements":"Erfolge",
		"credits":"Autoren",
		"quit":"Spiel verlassen",
	},
	"slovenčina":{
		"start":"Začať hru",
		"load":"Načítať  hru",
		"options":"Nastavenie",
		"achievements":"Úspechy",
		"credits":"Autori",
		"quit":"Ukončiť hru",
	},
	"français":{
		"start":"Commencer le jeu",
		"load":"Charger le jeu",
		"options":"Réglages",
		"achievements":"Réalisations",
		"credits":"Auteurs",
		"quit":"Quitter le jeu",
	},
	"italiano":{
		"start":"Inizia il gioco",
		"load":"Caricare il gioco",
		"options":"Impostazioni",
		"achievements":"Realizzazioni",
		"credits":"Autori",
		"quit":"Abbandonare il gioco",
	},
	"русский":{
		"start":"Начать игру",
		"load":"Загрузите игру",
		"options":"Настройки",
		"achievements":"Достижения",
		"credits":"Авторы",
		"quit":"Выйти из игры",
	},
	"español":{
		"start":"Empieza el juego",
		"load":"Cargar juego",
		"options":"Configuraciones",
		"achievements":"Logros",
		"credits":"Autores",
		"quit":"Salir del juego",
	},
	"português":{
		"start":"Comece o jogo",
		"load":"Carregar jogo",
		"options":"Configurações",
		"achievements":"conquistas",
		"credits":"Autores",
		"quit":"Desistir do jogo",
	}
}

func translate(texts, other_language):
	for key in texts.keys():
		texts[key].text = languages[other_language][key]
		
		if "bbcode_text" in texts[key]:
			texts[key].bbcode_text = "[center]"+languages[other_language][key]
